class DatabasePrivilegeValues:
    MODIFY = "MODIFY"
    MONITOR = "MONITOR"
    USAGE = "USAGE"
    CREATE_SCHEMA = "CREATE SCHEMA"
    IMPORTED_PRIVILEGES = "IMPORTED PRIVELEGES"
    ALL = "ALL"
    OWNERSHIP = "OWNERSHIP"
